version: '3.8'
services:
  app:
    build: .
    container_name: app
    volumes:
      - .:/app
    ports:
      - 3000:3000

  db:
    image: postgres
    container_name: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres

    volumes:
      - dbdata:/var/lib/postgresql/data

volumes:
  dbdata:
    driver: local

